version: "3.3"

services:
  # restrict plex for now so we don't have to worry about bots etc.
  plex:
    labels:
      - traefik.http.routers.plex.middlewares=internalwhitelist@docker
  sabnzbd:
    labels:
      - traefik.http.routers.sabnzbd.middlewares=internalwhitelist@docker
  whoami:
    labels:
      - traefik.http.routers.whoami.middlewares=internalwhitelist@docker
  watchtower:
    labels:
      - traefik.http.routers.watchtower.middlewares=internalwhitelist@docker
  sonarr:
    labels:
      - traefik.http.routers.sonarr.middlewares=internalwhitelist@docker
  radarr:
    labels:
      - traefik.http.routers.radarr.middlewares=internalwhitelist@docker    
  bazarr:
    labels:
      - traefik.http.routers.bazarr.middlewares=internalwhitelist@docker
  jackett:
    labels:
      - traefik.http.routers.jackett.middlewares=internalwhitelist@docker
  nzbhydra2:
    labels:
      - traefik.http.routers.nzbhydra2.middlewares=internalwhitelist@docker
  portainer:
    labels:
      - traefik.http.routers.portainer.middlewares=internalwhitelist@docker
  portainer_agent:
    labels:
      - traefik.http.routers.portainer_agent.middlewares=internalwhitelist@docker 
  organizr:
      labels:
      - traefik.http.routers.organizr.middlewares=internalwhitelist@docker
  duplicati:
    labels:
      - traefik.http.routers.duplicati.middlewares=internalwhitelist@docker
  traefik:
    labels:
      - traefik.http.routers.traefik.middlewares=internalwhitelist@docker
  vpn:
    labels:
      - traefik.http.routers.vpn.middlewares=internalwhitelist@docker
  deluge:
    labels:
      - traefik.http.routers.deluge.middlewares=internalwhitelist@docker
