version: "3.3"

services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    networks:
      - internal
    ports: 
      - 8112:8112
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`deluge.${DOMAIN}`)
      - traefik.http.routers.deluge.entrypoints=websecure
      - traefik.http.routers.deluge.tls.certresolver=myresolver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/deluge/config:/config
      - ${DOWNLOADS}/torrents:/downloads
      - ./themes/deluge/${DELUGE_THEME}.css:/usr/lib/python3/dist-packages/deluge/ui/web/themes/css/xtheme-gray.css
    restart: unless-stopped
