version: "3.3"

services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    networks:
      - web
    ports:
      - 8083:8083
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.calibreweb.rule=Host(`calibre-web.${DOMAIN}`)
      - traefik.http.routers.calibreweb.entrypoints=https
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ${CONTAINERS}/calibre-web/config:/config
      - ${CONTAINERS}/calibre-web/books:/books
    restart: unless-stopped
