version: "3.3"

#
# This file enables SSO via Google Cloud OAUTH.  Additionally, it layers in rate limiting.
#
# @credit https://www.smarthomebeginner.com/google-oauth-with-traefik-2-docker/
#
services:
  traefik:
    labels:
      # -----------------------------
      # Define reusable middlewares
      # -----------------------------
      - traefik.http.middlewares.sso.forwardauth.address=http://oauth:4181
      - traefik.http.middlewares.sso.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.sso.forwardauth.authResponseHeaders=X-Forwarded-User

      # rate limit
      - traefik.http.middlewares.rate-limit.rateLimit.average=100
      - traefik.http.middlewares.rate-limit.rateLimit.burst=50

      # -----------------------------
      # Define chain
      # -----------------------------
      - traefik.http.middlewares.chain-oauth.chain.middlewares=rate-limit,sso

      # -----------------------------
      # Apply middlewares to dashboard UI
      # -----------------------------
      - traefik.http.routers.traefik.middlewares=chain-oauth@docker

  oauth:
    restart: always
    container_name: oauth
    image: thomseddon/traefik-forward-auth
    # Allow apps to bypass OAuth. Radarr example below will bypass OAuth if API key is present in the request (eg. from NZB360 mobile app).
    # While this is one way, the recommended way is to bypass authentication using Traefik labels shown in some of the apps later.
    # command: --rule.radarr.action=allow --rule.radarr.rule=Headers(`X-Api-Key`, `$RADARR_API_KEY`)
    # command: --rule.sabnzbd.action=allow --rule.sabnzbd.rule=HeadersRegexp(`X-Forwarded-Uri`, `$SABNZBD_API_KEY`)
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GCP_OAUTH_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GCP_OAUTH_CLIENT_SECRET}
      - SECRET=${OAUTH_SECRET}
      - COOKIE_DOMAIN=${DOMAIN}
      - AUTH_HOST=oauth.${DOMAIN}
      - URL_PATH=${OAUTH_PATH}
      - LOG_LEVEL=debug
      - LOG_FORMAT=pretty
    labels:
      - traefik.enable=true
      # -----------------------------
      # HTTP Routers
      # -----------------------------
      - traefik.http.routers.oauth.entrypoints=https
      # -----------------------------
      # HTTP Services
      # -----------------------------
      - traefik.http.services.oauth.loadbalancer.server.port=4181
      - traefik.http.routers.oauth.service=oauth
    networks:
      - web

  whoami:
    labels:
      - traefik.http.routers.whoami.middlewares=chain-oauth@docker

  # traefik:
  #   labels:
  #     - traefik.http.routers.traefik.middlewares=chain-oauth@docker
  # plex:
  #   labels:
  #     - traefik.http.routers.plex.middlewares=chain-oauth@docker
  # sabnzbd:
  #   labels:
  #     - traefik.http.routers.sabnzbd.middlewares=chain-oauth@docker
  # sonarr:
  #   labels:
  #     - traefik.http.routers.sonarr.middlewares=chain-oauth@docker
  # radarr:
  #   labels:
  #     - traefik.http.routers.radarr.middlewares=chain-oauth@docker    
  # bazarr:
  #   labels:
  #     - traefik.http.routers.bazarr.middlewares=chain-oauth@docker
  # jackett:
  #   labels:
  #     - traefik.http.routers.jackett.middlewares=chain-oauth@docker
  # nzbhydra2:
  #   labels:
  #     - traefik.http.routers.nzbhydra2.middlewares=chain-oauth@docker
  # portainer:
  #   labels:
  #     - traefik.http.routers.portainer.middlewares=chain-oauth@docker
  # organizr:
  #     labels:
  #     - traefik.http.routers.organizr.middlewares=chain-oauth@docker
  # duplicati:
  #   labels:
  #     - traefik.http.routers.duplicati.middlewares=chain-oauth@docker
  # vpn:
  #   labels:
  #     - traefik.http.routers.vpn.middlewares=chain-oauth@docker
  # deluge:
  #   labels:
  #     - traefik.http.routers.deluge.middlewares=chain-oauth@docker