version: "3.3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    networks:
      - web
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=https
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.middlewares=internalwhitelist@docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - ADVERTISE_IP="https://plex.${DOMAIN}:443"
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_THEME=${TP_THEME}
    volumes:
      - ${CONTAINERS}/plex/config:/config
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - web
    ports:
      - 8989:8989
    depends_on:
      - sabnzbd
      - prowlarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=https
      - traefik.http.routers.sonarr.middlewares=internalwhitelist@docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${CONTAINERS}/sonarr/config:/config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - web
    ports:
      - 7878:7878
    depends_on:
      - sabnzbd
      - prowlarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=https
      - traefik.http.routers.radarr.middlewares=internalwhitelist@docker    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${CONTAINERS}/radarr/config:/config
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - web    
    ports:
      - 9696:9696
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=https
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.middlewares=internalwhitelist@docker    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${CONTAINERS}/prowlarr/config:/config
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    networks:
      - web
    ports:
      - 9050:8080
      - 9051:9090
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.entrypoints=https
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.routers.sabnzbd.middlewares=internalwhitelist@docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd
      - TP_THEME=${TP_THEME}
    volumes:
      - ${CONTAINERS}/sabnzbd/config:/config
      - ${DOWNLOADS}/sabnzbd:/downloads
    restart: unless-stopped

  # Organize a single page with tabs to manage all services.
  organizr:
    image: organizr/organizr
    container_name: organizr
    networks:
      - web
    ports:
      - 9983:80
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.orzanizr.entrypoints=https
      - traefik.http.services.organizr.loadbalancer.server.port=80
      - traefik.http.routers.organizr.middlewares=internalwhitelist@docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/organizr:/config
    restart: unless-stopped

