version: "3.3"

# Base file that must be used with a network topology.  See torrents-on-network.yml and torrents-on-vpn.yml for usage.
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.deluge.entrypoints=https
      - traefik.http.routers.deluge.middlewares=exposedAllowList@docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/deluge/config:/config
      - ${DOWNLOADS}/torrents:/downloads
      - ./themes/deluge/${DELUGE_THEME}.css:/usr/lib/python3/dist-packages/deluge/ui/web/themes/css/xtheme-gray.css
    restart: unless-stopped
